name: BuildAndUploadApk

on:
  push:
    branches: [upload-apk-github-action]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Debug Apk
        action: ./gradlew assembleDebug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: app/build/outputs/apk/debug/app-debug.apk