name: BuildAndUploadApk

on:
  push:
    branches: [upload-apk-github-action]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1

#      - name: Create Google Services JSON File
#        run: echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -di > app/google-services.json

      - name: Create Google Services Json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Cat services json
        run: cat app/google-services.json

      - name: Build Debug Apk
        run: ./gradlew assembleDebug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: app/build/outputs/apk/debug/app-debug.apk
